// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_ULH9XeeTprFea-2dMWnLtbgjBMTlgTI',
    appId: '1:756773483879:web:97436fcf0d8c5128896bc2',
    messagingSenderId: '756773483879',
    projectId: 'flutter-practice-f5f1a',
    authDomain: 'flutter-practice-f5f1a.firebaseapp.com',
    storageBucket: 'flutter-practice-f5f1a.appspot.com',
    measurementId: 'G-L0DSWVL0X1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIePN0xJ3RmtKuBStRAolLueNmD9hHHxA',
    appId: '1:756773483879:android:ba727a67f4bbc197896bc2',
    messagingSenderId: '756773483879',
    projectId: 'flutter-practice-f5f1a',
    storageBucket: 'flutter-practice-f5f1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTm-rAABadPJ5VNX0s2muwLe4mqdV3VQk',
    appId: '1:756773483879:ios:109a2b3d27bcf289896bc2',
    messagingSenderId: '756773483879',
    projectId: 'flutter-practice-f5f1a',
    storageBucket: 'flutter-practice-f5f1a.appspot.com',
    iosClientId: '756773483879-po6s6tpugs89vqk8tldc13kgqcl6pboo.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPractice',
  );
}
